name: Preview

on:
  pull_request:
    branches: ["main", "develop"]

permissions:
  contents: write
  pages: write
  deployments: write
  id-token: write
  issues: write
  pull-requests: write

jobs:
  storybook-preview:
    runs-on: ubuntu-latest
    steps:
      - name: 저장소 체크아웃
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Node.js 설정
        uses: actions/setup-node@v3
        with:
          node-version: "20"
          cache: "yarn"

      - name: 종속성 설치
        run: yarn install --frozen-lockfile

      - name: Chromatic에 게시
        id: chromatic
        uses: chromaui/action@v1
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          token: ${{ secrets.GITHUB_TOKEN }}
          onlyChanged: true
          autoAcceptChanges: true
          exitZeroOnChanges: true

    outputs:
      storybook_url: ${{ steps.chromatic.outputs.storybookUrl }}

  github-bot-storybook:
    runs-on: ubuntu-latest
    needs: [storybook-preview]
    steps:
      - name: 현재 시간 가져오기
        uses: josStorer/get-current-time@v2
        id: current-time
        with:
          format: "YYYY년 MM월 DD일 HH시 mm분 ss초"
          utcOffset: "+09:00"

      - name: PR 코멘트 남기기
        uses: thollander/actions-comment-pull-request@v2
        with:
          comment_tag: ${{github.event.number}}-storybook
          message: |
            💄 Storybook: ${{ needs.storybook-preview.outputs.storybook_url }}
            🕖 Update: ${{ steps.current-time.outputs.formattedTime }}
